### ISSUE TITLE
GBC Konami GB Collection 2&4 not working

### ISSUE THREAD

**Issue by AbnormalFreak** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#119]
This is for the PAL Game Boy Color versions of the series. Collections 2 and 4 don't work in the GBC core. They display the GBC startup screen but then get stuck on a blank white screen. Konami GB Collection Vol.4 (Europe) includes the color version of Castlevania II: Belmont's Revenge, which would really be cool to play. I've tried ROMs from two different sources and neither work, though they do play on emulators. Every other GBC ROM I've thrown at it (including Konami GB Collection Vol.1 and 3) works great so I don't know why these don't.

**Comment by tjanas** [comment]
Provide checksums of your files.

**Comment by burbruee** [comment]
I can confirm this issue. This bug is present both on the old Nt Mini as well as on the Noir jailbreak.
It's odd that Vol 1 boots, they use the same mapper (MBC5) and I compared the header and they're identical.

The game works on the GB core as it is backwards compatible (black cartridge), but then of course you don't get the color as well as the advantages of running on GBC hardware. They optimized the games for GBC hardware and will have no lag in game. (at least Belmont's Revenge, can't speak for the other games)

md5: f3414d53473e2cc43347774cc5f40495  Konami GB Collection Vol.4 (E) [C][!].gbc

**Comment by matthargett** [comment]
Confirmed to be reproducible on JB 6.6. Even the Konami GB Collection “speed hack” variants in the Hacks directory of the SmokeMonster pack are affected.

**Comment by tjanas** [comment]
@AbnormalFreak @burbruee @matthargett Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
