### ISSUE TITLE
RetroUSB 8-BIT XMAS 2016 glitched

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#71]
Using https://retrousb.com/downloads/xmas16demo.nes after running NES2.0 XML script to modify the header to a correct header. Graphics on the Nt Mini Noir are glitched with this rom.
![42AD2129-F556-4941-89C3-627C5AAA70ED](https://user-images.githubusercontent.com/20304619/102744969-ad461d80-4320-11eb-9bf1-076a73543a4a.jpeg)

**Comment by GreatHierophant** [comment]
They're glitched period, that is a bad dump.

**Comment by tjanas** [comment]
Weird that that creator of the game would host a bad rom dump.

**Comment by spspspspspsp** [comment]
I know this issue was closed, but I am also curious about this.

Is this really a bad dump?

It looks like could be incomplete, based on retroUSB's YouTube videos, but [this page](https://www.retrousb.com/product_info.php?cPath=31&products_id=152&osCsid=d8851490489c375d51fac5d462941fb2) also says this ROM is "for archival purposes only. No emulator support."
